### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by 41ien** [wupco/PHP_INCLUDE_TO_SHELL_CHAR_DICT#1]
师傅好，感谢师傅的 fuzz，我想请教两个问题
1. 您的 fuzzer.php 该怎么运行呢
2. fuzzer.php 中第44行的那个 while 循环，为什么要用 rand 呢
感谢 : )

**Comment by wupco** [comment]
1. 直接跑就行了，不需要参数
2. rand是随机选择一个编码

**Comment by 41ien** [comment]
> 1. 直接跑就行了，不需要参数
> 2. rand是随机选择一个编码

1. 我跑了半个小时都没有结果，以为是用法有问题，您那大概跑了多久才跑出来的呢
2. 为什么不挨着遍历，而是随机呢（就是单纯地想知道）

**Comment by wupco** [comment]
> 



> > 1. 直接跑就行了，不需要参数
> > 2. rand是随机选择一个编码
> 
> 1. 我跑了半个小时都没有结果，以为是用法有问题，您那大概跑了多久才跑出来的呢
> 2. 为什么不挨着遍历，而是随机呢（就是单纯地想知道）

1. 最开始很难出结果，机器条件好建议多跑几个，一起跑，等出来一些之后效率就高一些了。
2. 随机更容易提前碰撞出结果，一次要套用好几个filter，遍历效率肯定会差很多。

**Comment by 41ien** [comment]
> > 
> 
> > > 1. 直接跑就行了，不需要参数
> > > 2. rand是随机选择一个编码
> > 
> > 
> > 
> > 1. 我跑了半个小时都没有结果，以为是用法有问题，您那大概跑了多久才跑出来的呢
> > 2. 为什么不挨着遍历，而是随机呢（就是单纯地想知道）
> 
> 1. 最开始很难出结果，机器条件好建议多跑几个，一起跑，等出来一些之后效率就高一些了。
> 2. 随机更容易提前碰撞出结果，一次要套用好几个filter，遍历效率肯定会差很多。

明白了，感谢师傅的不吝赐教 : )

> > 
> 
> > > 1. 直接跑就行了，不需要参数
> > > 2. rand是随机选择一个编码
> > 
> > 
> > 
> > 1. 我跑了半个小时都没有结果，以为是用法有问题，您那大概跑了多久才跑出来的呢
> > 2. 为什么不挨着遍历，而是随机呢（就是单纯地想知道）
> 
> 1. 最开始很难出结果，机器条件好建议多跑几个，一起跑，等出来一些之后效率就高一些了。
> 2. 随机更容易提前碰撞出结果，一次要套用好几个filter，遍历效率肯定会差很多。

明白了，感谢师傅的不吝赐教 : )

**Comment by 41ien** [comment]
> > 
> 
> > > 1. 直接跑就行了，不需要参数
> > > 2. rand是随机选择一个编码
> > 
> > 
> > 
> > 1. 我跑了半个小时都没有结果，以为是用法有问题，您那大概跑了多久才跑出来的呢
> > 2. 为什么不挨着遍历，而是随机呢（就是单纯地想知道）
> 
> 1. 最开始很难出结果，机器条件好建议多跑几个，一起跑，等出来一些之后效率就高一些了。
> 2. 随机更容易提前碰撞出结果，一次要套用好几个filter，遍历效率肯定会差很多。

明白了，感谢师傅的不吝赐教 : )

**Comment by wupco** [comment]
> > > 
> > 
> > 
> > > > 1. 直接跑就行了，不需要参数
> > > > 2. rand是随机选择一个编码
> > > 
> > > 
> > > 
> > > 1. 我跑了半个小时都没有结果，以为是用法有问题，您那大概跑了多久才跑出来的呢
> > > 2. 为什么不挨着遍历，而是随机呢（就是单纯地想知道）
> > 
> > 
> > 
> > 1. 最开始很难出结果，机器条件好建议多跑几个，一起跑，等出来一些之后效率就高一些了。
> > 2. 随机更容易提前碰撞出结果，一次要套用好几个filter，遍历效率肯定会差很多。
> 
> 明白了，感谢师傅的不吝赐教 : )

你要换系统环境，一定要记得改一下这里 https://github.com/wupco/PHP_INCLUDE_TO_SHELL_CHAR_DICT/blob/main/fuzzer.php#L11
这里的值通过iconv -l列出
多个fuzzer一起跑建议都在同一个目录下，这样他们的结果是共享的，seed也是共享的

**Comment by 41ien** [comment]
> > > > 
> > > 
> > > 
> > > > > 1. 直接跑就行了，不需要参数
> > > > > 2. rand是随机选择一个编码
> > > > 
> > > > 
> > > > 
> > > > 1. 我跑了半个小时都没有结果，以为是用法有问题，您那大概跑了多久才跑出来的呢
> > > > 2. 为什么不挨着遍历，而是随机呢（就是单纯地想知道）
> > > 
> > > 
> > > 
> > > 1. 最开始很难出结果，机器条件好建议多跑几个，一起跑，等出来一些之后效率就高一些了。
> > > 2. 随机更容易提前碰撞出结果，一次要套用好几个filter，遍历效率肯定会差很多。
> > 
> > 
> > 明白了，感谢师傅的不吝赐教 : )
> 
> 你要换系统环境，一定要记得改一下这里 https://github.com/wupco/PHP_INCLUDE_TO_SHELL_CHAR_DICT/blob/main/fuzzer.php#L11 这里的值通过iconv -l列出 多个fuzzer一起跑建议都在同一个目录下，这样他们的结果是共享的，seed也是共享的

OK，感谢！！！
