### ISSUE TITLE
Windows 下使用会导致res/下的大写字母被吃掉

### ISSUE THREAD

**Issue by mrjesen** [wupco/PHP_INCLUDE_TO_SHELL_CHAR_DICT#2]
Windows 下使用会导致res/下的大写字母被吃掉

**Comment by wupco** [comment]
[fixed](https://github.com/wupco/PHP_INCLUDE_TO_SHELL_CHAR_DICT/commit/3e9542d82d29be5df5155117c5c7b109c4a88f98#diff-3665d65394f4f58a56a256ad6dd8621c68118d90fe56a19387e251c19cec2d2e)
